#!/usr/bin/env python3
"""NASA/JPL update engine shared by the desktop server and CLI updater."""
from __future__ import annotations

import datetime as dt
import json
import threading
import time
import urllib.error
from pathlib import Path
from typing import Any, Callable, Final

from database import (
    DB_PATH,
    begin_update_run,
    counts,
    finish_update_run,
    replace_close_approaches,
    replace_fireballs,
    replace_sentry,
    set_metadata,
    upsert_object_profile,
    backup_database,
    restore_database,
    remove_database_backup,
)
from jpl_client import ensure_signature, request_json, signature_info
from runtime_paths import LIVE_CACHE_PATH

CACHE_PATH: Final[Path] = LIVE_CACHE_PATH
VERSION: Final[str] = "0.7.2"

ProgressCallback = Callable[[dict[str, Any]], None]


class UpdateCancelled(RuntimeError):
    pass


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def fetch_json(
    base_url: str,
    params: dict[str, Any] | None = None,
    *,
    timeout: int = 45,
    attempts: int = 3,
) -> dict[str, Any]:
    return request_json(
        base_url, params, timeout=timeout, attempts=attempts,
        user_agent=f"AsteroidArchiveUpdater/{VERSION} (+local scientific archive)",
    )

def records(payload: dict[str, Any]) -> list[dict[str, Any]]:
    data = payload.get("data")
    fields = payload.get("fields")
    if isinstance(data, list) and data:
        if isinstance(data[0], list) and isinstance(fields, list):
            return [dict(zip(fields, row)) for row in data]
        if isinstance(data[0], dict):
            return [dict(row) for row in data if isinstance(row, dict)]
    if isinstance(data, list):
        return []
    # Some JPL endpoints may return a top-level list under a named collection.
    for key in ("objects", "results"):
        value = payload.get(key)
        if isinstance(value, list):
            return [dict(row) for row in value if isinstance(row, dict)]
    return []


def _emit(callback: ProgressCallback | None, logs: list[dict[str, Any]], stage: str, percent: int, message: str, **extra: Any) -> None:
    item = {"time": utc_now(), "stage": stage, "percent": max(0, min(100, int(percent))), "message": message, **extra}
    logs.append(item)
    if callback:
        callback(item)


def _check_cancel(cancel_event: threading.Event | None) -> None:
    if cancel_event and cancel_event.is_set():
        raise UpdateCancelled("Update cancelled by user")


def write_cache(
    generated_at: str,
    approaches: list[dict[str, Any]],
    fireballs: list[dict[str, Any]],
    sentry: list[dict[str, Any]],
    signatures: dict[str, Any],
) -> None:
    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    cache = {
        "generated_at": generated_at,
        "closeApproaches": approaches,
        "fireballs": fireballs,
        "sentry": sentry,
        "signatures": signatures,
    }
    text = (
        "/* Generated by Asteroid Archive NASA Data Engine v0.7 — do not edit manually. */\n"
        + "window.AA_LIVE_CACHE = "
        + json.dumps(cache, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )
    temp_path = CACHE_PATH.with_suffix(CACHE_PATH.suffix + ".tmp")
    temp_path.write_text(text, encoding="utf-8")
    temp_path.replace(CACHE_PATH)


def run_update(
    config: dict[str, Any] | None = None,
    *,
    progress: ProgressCallback | None = None,
    cancel_event: threading.Event | None = None,
    trigger: str = "manual",
) -> dict[str, Any]:
    config = dict(config or {})
    days = max(1, min(int(config.get("days", 365)), 3650))
    distance_ld = max(0.1, min(float(config.get("distance_ld", 10)), 500.0))
    approach_limit = max(1, min(int(config.get("approach_limit", 2000)), 20000))
    fireball_limit = max(1, min(int(config.get("fireball_limit", 2000)), 20000))
    profile_limit = max(0, min(int(config.get("profile_limit", 30)), 250))
    include_profiles = bool(config.get("include_profiles", True)) and profile_limit > 0
    config = {
        "days": days,
        "distance_ld": distance_ld,
        "approach_limit": approach_limit,
        "fireball_limit": fireball_limit,
        "profile_limit": profile_limit,
        "include_profiles": include_profiles,
    }

    logs: list[dict[str, Any]] = []
    run_id = begin_update_run(trigger, config)
    backup_path: Path | None = None
    generated_at = utc_now()
    start_date = dt.date.today()
    end_date = start_date + dt.timedelta(days=days)

    try:
        backup_path = backup_database()
        _emit(progress, logs, "initialize", 2, "تهيئة محرك بيانات NASA/JPL", run_id=run_id)
        _check_cancel(cancel_event)

        # Download all core datasets before replacing any local table. This preserves
        # the last complete database if one of the remote services fails mid-update.
        _emit(progress, logs, "cad_download", 8, "تنزيل سجل الاقترابات القريبة")
        cad_payload = fetch_json(
            "https://ssd-api.jpl.nasa.gov/cad.api",
            {
                "date-min": start_date.isoformat(),
                "date-max": end_date.isoformat(),
                "dist-max": f"{distance_ld}LD",
                "diameter": "true",
                "fullname": "true",
                "limit": approach_limit,
                "sort": "date",
                "body": "Earth",
            },
        )
        ensure_signature(cad_payload, "cad")
        approach_rows = [{**row, "source_mode": "cache"} for row in records(cad_payload)]
        _check_cancel(cancel_event)

        _emit(progress, logs, "fireball_download", 22, "تنزيل سجل الكرات النارية والانفجارات الجوية")
        fireball_payload = fetch_json(
            "https://ssd-api.jpl.nasa.gov/fireball.api",
            {"limit": fireball_limit, "sort": "-date"},
        )
        ensure_signature(fireball_payload, "fireball")
        fireball_rows = [{**row, "source_mode": "cache"} for row in records(fireball_payload)]
        _check_cancel(cancel_event)

        _emit(progress, logs, "sentry_download", 36, "تنزيل قائمة CNEOS Sentry الاحتمالية")
        sentry_payload = fetch_json("https://ssd-api.jpl.nasa.gov/sentry.api")
        ensure_signature(sentry_payload, "sentry")
        sentry_rows = [{**row, "source_mode": "cache"} for row in records(sentry_payload)]
        _check_cancel(cancel_event)

        _emit(progress, logs, "core_verify", 47, "اكتملت التنزيلات الأساسية؛ بدء الحفظ الذري للمجموعات")
        _emit(progress, logs, "cad_store", 50, f"حفظ {len(approach_rows)} سجل اقتراب في SQLite")
        replace_close_approaches(approach_rows)
        _emit(progress, logs, "fireball_store", 53, f"حفظ {len(fireball_rows)} سجل كرة نارية في SQLite")
        replace_fireballs(fireball_rows)
        _emit(progress, logs, "sentry_store", 57, f"حفظ {len(sentry_rows)} جسم مراقب في SQLite")
        replace_sentry(sentry_rows)

        profiles_ok = 0
        profiles_failed = 0
        if include_profiles:
            # Priority: nearest approaches first, then active Sentry objects. Duplicate designations are removed.
            def distance_key(row: dict[str, Any]) -> float:
                try:
                    return float(row.get("dist"))
                except (TypeError, ValueError):
                    return 9e9

            approach_sorted = sorted(approach_rows, key=distance_key)
            candidates: list[str] = []
            seen: set[str] = set()
            for row in approach_sorted + sentry_rows:
                des = str(row.get("des") or "").strip()
                if des and des not in seen:
                    seen.add(des)
                    candidates.append(des)
                if len(candidates) >= profile_limit:
                    break
            total = max(1, len(candidates))
            for index, designation in enumerate(candidates, start=1):
                _check_cancel(cancel_event)
                percent = 58 + round((index - 1) / total * 27)
                _emit(progress, logs, "profile_download", percent, f"تحميل الملف العلمي {index}/{len(candidates)}: {designation}", designation=designation)
                try:
                    profile = fetch_json(
                        "https://ssd-api.jpl.nasa.gov/sbdb.api",
                        {"sstr": designation, "phys-par": "true", "full-prec": "true"},
                    )
                    ensure_signature(profile, "sbdb")
                    upsert_object_profile(profile)
                    profiles_ok += 1
                except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError, ValueError, RuntimeError, json.JSONDecodeError) as exc:
                    profiles_failed += 1
                    _emit(progress, logs, "profile_warning", percent, f"تعذر حفظ ملف {designation}: {exc}", designation=designation, warning=True)
                time.sleep(0.20)
        else:
            _emit(progress, logs, "profiles_skip", 82, "تخطي التحديث الجماعي للملفات العلمية حسب الإعداد")

        signatures = {
            "cad": signature_info(cad_payload, "cad"),
            "fireball": signature_info(fireball_payload, "fireball"),
            "sentry": signature_info(sentry_payload, "sentry"),
        }
        mismatches = [name for name, info in signatures.items() if info.get("version_match") is False]
        if mismatches:
            _emit(progress, logs, "version_warning", 86, f"تحذير: تغير إصدار API للخدمات: {', '.join(mismatches)}", warning=True)
        _check_cancel(cancel_event)
        _emit(progress, logs, "cache", 88, "إنشاء نسخة بيانات احتياطية للعمل دون إنترنت")
        write_cache(generated_at, approach_rows, fireball_rows, sentry_rows, signatures)

        set_metadata("generated_at", generated_at)
        set_metadata("date_min", start_date.isoformat())
        set_metadata("date_max", end_date.isoformat())
        set_metadata("distance_ld", distance_ld)
        set_metadata("api_signatures", signatures)
        set_metadata("engine_version", VERSION)
        set_metadata("last_update_status", "success")

        result_counts = counts()
        result_counts.update({"profiles_updated": profiles_ok, "profiles_failed": profiles_failed})
        _emit(progress, logs, "verify", 96, "فحص قاعدة البيانات وسجل التحديث", counts=result_counts)
        _emit(progress, logs, "complete", 100, "اكتمل تحديث NASA/JPL بنجاح", counts=result_counts, run_id=run_id)
        finish_update_run(run_id, "success", result_counts, logs)
        if backup_path is not None:
            remove_database_backup(backup_path)
        return {
            "status": "success",
            "run_id": run_id,
            "generated_at": generated_at,
            "config": config,
            "counts": result_counts,
            "signatures": signatures,
            "logs": logs,
            "database": str(DB_PATH),
            "cache": str(CACHE_PATH),
        }
    except UpdateCancelled as exc:
        if backup_path is not None:
            restore_database(backup_path)
        set_metadata("last_update_status", "cancelled")
        _emit(progress, logs, "cancelled", 100, "أُلغي التحديث مع الإبقاء على آخر بيانات سليمة", run_id=run_id)
        finish_update_run(run_id, "cancelled", counts(), logs, str(exc))
        if backup_path is not None:
            remove_database_backup(backup_path)
        return {"status": "cancelled", "run_id": run_id, "error": str(exc), "logs": logs, "counts": counts()}
    except Exception as exc:
        if backup_path is not None:
            restore_database(backup_path)
        set_metadata("last_update_status", "failed")
        _emit(progress, logs, "failed", 100, f"فشل التحديث: {exc}", error=True, run_id=run_id)
        finish_update_run(run_id, "failed", counts(), logs, str(exc))
        if backup_path is not None:
            remove_database_backup(backup_path)
        raise
